backend:
  name: local
  # name: git-gateway
  # branch: main

# Configuração para desenvolvimento local
local_backend: true

# Configurações gerais
site_url: http://localhost:8081
display_url: http://localhost:8081

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "public/blog-posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Autor", name: "author", widget: "string", default: "Equipe Nodal Energy" }
      - { label: "Data", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Categoria", name: "category", widget: "select", options: ["Energia Solar", "Eficiência Energética", "Tributário", "Sustentabilidade", "Inovação"] }
      - { label: "Tempo de Leitura", name: "readTime", widget: "string", default: "5 min" }
      - { label: "Destaque", name: "featured", widget: "boolean", default: false }
      - { label: "Resumo", name: "excerpt", widget: "text", hint: "Breve descrição do artigo" }
      - { label: "Conteúdo", name: "content", widget: "markdown", hint: "Conteúdo completo do artigo" }
      - { label: "Imagem de Capa", name: "coverImage", widget: "image", required: false }
      - { label: "Tags", name: "tags", widget: "list", field: { label: "Tag", name: "tag", widget: "string" }, required: false }
      - { label: "SEO - Meta Description", name: "metaDescription", widget: "text", required: false }
      - { label: "SEO - Keywords", name: "keywords", widget: "list", field: { label: "Keyword", name: "keyword", widget: "string" }, required: false }

  - name: "config"
    label: "Configurações do Site"
    files:
      - file: "src/data/siteConfig.json"
        label: "Configurações Gerais"
        name: "siteConfig"
        fields:
          - { label: "Nome do Site", name: "siteName", widget: "string", default: "Nodal Energy" }
          - { label: "Descrição", name: "description", widget: "text" }
          - { label: "Email de Contato", name: "contactEmail", widget: "string" }
          - { label: "Telefone", name: "phone", widget: "string" }
          - { label: "Endereço", name: "address", widget: "text" }
          - label: "Redes Sociais"
            name: "socialMedia"
            widget: "object"
            fields:
              - { label: "LinkedIn", name: "linkedin", widget: "string", required: false }
              - { label: "Instagram", name: "instagram", widget: "string", required: false }
              - { label: "Facebook", name: "facebook", widget: "string", required: false } 