backend:
  name: local
  local_backend: true

local_backend: true

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "public/blog-posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string", required: true}
      - {label: "Autor", name: "author", widget: "string", required: true}
      - {label: "Data", name: "date", widget: "datetime", required: true}
      - {label: "Categoria", name: "category", widget: "select", options: ["Energia Solar", "Energia Eólica", "Eficiência Energética", "Sustentabilidade", "Tecnologia"], required: true}
      - {label: "Resumo", name: "excerpt", widget: "text", required: true}
      - {label: "Conteúdo", name: "content", widget: "markdown", required: true}
      - {label: "Imagem de Capa", name: "coverImage", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Meta Description", name: "metaDescription", widget: "text", required: false}
      - {label: "Keywords", name: "keywords", widget: "text", required: false}

  - name: "config"
    label: "Configurações do Site"
    files:
      - file: "src/data/siteConfig.json"
        label: "Configurações Gerais"
        name: "siteConfig"
        fields:
          - {label: "Nome do Site", name: "siteName", widget: "string", required: true}
          - {label: "Descrição", name: "description", widget: "text", required: true}
          - {label: "Email de Contato", name: "contactEmail", widget: "string", required: true}
          - {label: "Telefone", name: "phone", widget: "string", required: false}
          - {label: "Endereço", name: "address", widget: "text", required: false}
          - label: "Redes Sociais"
            name: "socialMedia"
            widget: "object"
            fields:
              - {label: "Facebook", name: "facebook", widget: "string", required: false}
              - {label: "Instagram", name: "instagram", widget: "string", required: false}
              - {label: "LinkedIn", name: "linkedin", widget: "string", required: false}
              - {label: "YouTube", name: "youtube", widget: "string", required: false}
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
              - {label: "Meta Description", name: "metaDescription", widget: "text", required: false}
              - {label: "Keywords", name: "keywords", widget: "text", required: false}
              - {label: "Google Analytics", name: "googleAnalytics", widget: "string", required: false}
              - {label: "Google Tag Manager", name: "googleTagManager", widget: "string", required: false}

admin:
  title: "Nodal Energy - CMS"
  logo_url: "/images/logo.png"
  favicon_url: "/favicon.ico"
  css_url: "/admin/cms-custom.css"
  js_url: "/admin/cms-custom.js"

notifications:
  - type: "success"
    message: "Conteúdo salvo com sucesso!"
  - type: "error"
    message: "Erro ao salvar conteúdo. Tente novamente."

backup:
  enabled: true
  frequency: "daily" 